### ISSUE TITLE
Implement create account

### ISSUE THREAD

**Issue by jasonplojo** [kamikitty/ResilientSmartGarden#12]

**Comment by Marinela-S** [comment]
Serves as the registration page. Currently looking up angular examples of how to create the login and registration and cross referencing previous code to create the registration page based on angular instead of php

**Comment by Marinela-S** [comment]
Found a tutorial that seems to match my current directory set up and has all the necessities for login and register along with security. Will try to follow the tutorial focusing on functionality over design in the interest of time.

http://jasonwatmore.com/post/2017/02/22/mean-with-angular-2-user-registration-and-login-example-tutorial

**Comment by Marinela-S** [comment]
Current issue with setting secret. Still trying to figure out where the error is coming from. I messaged the blog i got the tutorial from for help but they still haven't gotten back
